const PREFIX = 'REACT_REDUX_EASY_FORM/';

export const SET_VALUE = PREFIX + 'SET_VALUE';
export const SET_INITIAL_VALUES = PREFIX + 'SET_INITIAL_VALUES';
export const VALIDATE_FIELD = PREFIX + 'VALIDATE_FIELD';
export const VALIDATE_FORM = PREFIX + 'VALIDATE_FORM';
export const DROP_FORM = PREFIX + 'DROP_FORM';
export const MAKE_DIRTY = PREFIX + 'MAKE_DIRTY';
export const MAKE_PRISTINE = PREFIX + 'MAKE_PRISTINE';